tck/src/main/java/org/reactivestreams/tck/IdentityProcessorVerification.java, tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/main/java/org/reactivestreams/tck/support/PublisherVerificationRules.java, tck/src/test/java/org/reactivestreams/tck/EmptyLazyPublisherTest.java, tck/src/test/java/org/reactivestreams/tck/PublisherVerificationTest.java, tck/src/test/java/org/reactivestreams/tck/SingleElementPublisherTest.java
Adapts the TCK to allow "0 length publishers", though only one test makes sense for them AFAICS.
This PR resolves #198 and adheres to current reactive streams rules about "it must fist give out an subscription" - as seen in the call-order-schema on https://github.com/reactive-streams/reactive-streams#api-components
Though there is an open question (from my end) about if this should be explicitly mentioned in the spec itself. (See #198 for a discussion).
=> +tck #198 allow 0-length publishers to be tested

tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java, tck/src/main/java/org/reactivestreams/tck/WithHelperPublisher.java
@reactive-streams/contributors This is just a bugfix PR to make RS javadoc succeed on JDK8, will merge when TravisCI clears it.
=> Fixes javadoc issues to make the build Java8 compliant

README.md
simply because I could not find appropriate wording.
**NOTE: No intentional semantical changes have been made. If you find issues, please, please, please let me know**
Harmonises the use of "call" and "invoke" to use "call" in all places
where "invoke" was used.
@reactive-streams/contributors Could you please sanity check the changes proposed here? Thanks!
Please vote/comment before the 21st of January (as always, if you need more time let us know)
=> Switches to positive wording for all rules besides 2.3,

README.md, examples/src/main/java/org/reactivestreams/example/unicast/AsyncIterablePublisher.java, tck/src/main/java/org/reactivestreams/tck/IdentityProcessorVerification.java, tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/main/java/org/reactivestreams/tck/support/PublisherVerificationRules.java, tck/src/test/java/org/reactivestreams/tck/PublisherVerificationTest.java
fixes #196
Also terminate spec rule sentences with a full stop where missing.
=> remove requirement to track demand beyond Long.MAX_VALUE

README.md
Resolves #206
The problem was introduced in https://github.com/reactive-streams/reactive-streams/commit/a3005b779344bf8ed6047d73d89ad9b39bb1d1a7 in which an ending `.` was added to each spec rule. By mistake it was also added to the table header, which broke the rendering :-)
=> Repairs formatting issue of tables in spec README

README.md
@reactive-streams/contributors This doesn't change the spec, just clarifies the "multi-subscribe" clause of `1.11`. If you disagree, please comment on this PR saying so before the 13th of February. Thanks in advance!
=> Fixes #211 by clarifying

README.md, examples/src/main/java/org/reactivestreams/example/unicast/AsyncIterablePublisher.java, examples/src/main/java/org/reactivestreams/example/unicast/AsyncSubscriber.java, examples/src/main/java/org/reactivestreams/example/unicast/SyncSubscriber.java, examples/src/test/java/org/reactivestreams/example/unicast/IterablePublisherTest.java, examples/src/test/java/org/reactivestreams/example/unicast/UnboundedIntegerIncrementPublisherTest.java, tck/src/main/java/org/reactivestreams/tck/IdentityProcessorVerification.java, tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/main/java/org/reactivestreams/tck/support/PublisherVerificationRules.java, tck/src/test/java/org/reactivestreams/tck/PublisherVerificationTest.java
@reactive-streams/contributors This is a proposal for spec amendment to fix #202 as discussed in that Issue, I will update the TCK appropriately if this proposal is accepted. Please vote before the 13th of February (or ask for an extension if you won't have time before that). Thank you!
=> Attempt to clarify the signalling sequence in the spec

tck/src/test/java/org/reactivestreams/tck/PublisherVerificationTest.java
Trivial name fixup, introduced in https://github.com/reactive-streams/reactive-streams/pull/214/files#diff-4ebca955800e47695d157fcd89b4fec6R263 
Notice that this rule is a required rule, thus the method name of the test should reflect this.
( see why such name here: https://github.com/reactive-streams/reactive-streams/pull/219/files#diff-4ebca955800e47695d157fcd89b4fec6R273 )
=> =tck minor test name fixup, it is a required test

examples/src/test/java/org/reactivestreams/example/unicast/IterablePublisherTest.java, examples/src/test/java/org/reactivestreams/example/unicast/UnboundedIntegerIncrementPublisherTest.java, tck/README.md, tck/src/main/java/org/reactivestreams/tck/IdentityProcessorVerification.java, tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/test/java/org/reactivestreams/tck/EmptyLazyPublisherTest.java, tck/src/test/java/org/reactivestreams/tck/IdentityProcessorVerificationTest.java, tck/src/test/java/org/reactivestreams/tck/PublisherVerificationTest.java, tck/src/test/java/org/reactivestreams/tck/SingleElementPublisherTest.java
+ add better readme on what this method is
+ add better javadoc on this method
- removes reference to old style spec annotation from readme
+ proposing to change method name to "createFailed..." as it is the wording used in the spec and reactive manifesto (footnote 1.1)
Resolves #237, #235
=> !tck - clarifies error publisher, and method name change (?)

CONTRIBUTING.md, CopyrightWaivers.txt, README.md, tck/README.md, tck/src/main/java/org/reactivestreams/tck/IdentityProcessorVerification.java, tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/main/java/org/reactivestreams/tck/SubscriberBlackboxVerification.java, tck/src/main/java/org/reactivestreams/tck/SubscriberWhiteboxVerification.java, tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java
Resolves #239  
Don't merge yet, I want to look though all other specs but lacked the capacity to have done this today.
Question that needs feedback here is if we want to rename the existing method to be less confusing - I say yes.
=> +TCK verifyNoAsyncErrors now by default waits, fixes spec111

tck/README.md, tck/src/test/java/org/reactivestreams/tck/IdentityProcessorVerificationDelegationTest.java
Readme updates so that it shows up to date code as well as explains the TCK upgrade story.
Resolves #99
Depends on #241
:airplane:
=> =tck general tck/readme.md cleanup so it matches current code / spec

api/src/main/java/org/reactivestreams/Publisher.java
Doesn't get more trivial than this PR. ```Publisher``` javadoc lacked a space.
=> Publisher: add space to javadoc

tck/README.md
=> +tck explains createElement in more useful terms

tck/README.md
=> +tck #232 explain which tests are mendatory to be "compliant"

tck/src/main/java/org/reactivestreams/tck/SubscriberBlackboxVerification.java, tck/src/test/java/org/reactivestreams/tck/SyncTriggeredDemandSubscriberTest.java, tck/src/test/java/org/reactivestreams/tck/SyncTriggeredDemandSubscriberWhiteboxTest.java, tck/src/test/java/org/reactivestreams/tck/support/SyncTriggeredDemandSubscriber.java
Fixes #233 @purplefox & @ktoso?
=> Fixes #233 by implementing support for triggered demand in in the SubscriberBlackboxVerification

.travis.yml
By validating on both JDKs we know the project even builds on 8,
while not using features (classes) from JDK8 - so it's still usable for JDK6 projects.
Resolves #254
=> Travis PR validation using both JDK 6 and 8

tck/README.md
@reactive-streams/contributors I went through the TCK README.md and made some fixes/edits/typo-corrections etc. Feel free to comment, I'm intending to merge it within 24h to ensure we can ship the next RC.
Ping @ktoso
=> Small touchups to the TCK README.md

tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/test/java/org/reactivestreams/tck/PublisherVerificationTest.java
=> Cancel the subscription after receiving all of the pertinent emissions (#259)

tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java
Removes unused and not documented method which may have lead to confusion on how to set up GC-timeout.
GC timeout it set up during creation of a verification, the same style as the default timeout in TestEnvironment, as documented here: https://github.com/reactive-streams/reactive-streams-jvm/commit/b17a364911cbde7bb594a490dd6159b0c8ada20a#diff-4ce068920e11452416705ccb8f46ec78R198
This PR removes an unused, configuring this value should be done as documented in tck/README.md
=> -tck rm undocumented and unused publisherReferenceGCTimeoutMillis method

tck/src/main/java/org/reactivestreams/tck/SubscriberBlackboxVerification.java, tck/src/main/java/org/reactivestreams/tck/support/SubscriberBlackboxVerificationRules.java
Minor typo in a method name - it is untested, this should have this prefix (as explained in tck/README.md)
=> =tck untested spec308 rule method name adjusted

README.md, build.gradle, tck/README.md
=> update ref to 1.0.0.final

CopyrightWaivers.txt, README.md
The document generally refers to "elements" as objects traversing a stream. I initially considered simply editing "processing elements" to read "processing components", but there's a section devoted to the definition of this, so better to link them.
=> Disambiguate "processing elements"

README.md
To make it visually obvious that CC0 applies to this work we might want to add this standard marker. What do you think, @reactive-streams/contributors ?
=> add CC0 label to README

CopyrightWaivers.txt, examples/src/main/java/org/reactivestreams/example/unicast/AsyncSubscriber.java, examples/src/main/java/org/reactivestreams/example/unicast/SyncSubscriber.java, examples/src/test/java/org/reactivestreams/example/unicast/SyncSubscriberTest.java, examples/src/test/java/org/reactivestreams/example/unicast/SyncSubscriberWhiteboxTest.java, tck/src/test/java/org/reactivestreams/tck/support/SyncTriggeredDemandSubscriber.java
AsyncSubscriber had a comment referring to `foreach` which is a method that exists in SyncSubscriber while in AsyncSubscriber it is called `whenNext`.
This PR also renames `foreach` in SyncSubscriber to `whenNext`. When I first looked at SyncSubscriber I had the impression there was a loop. It doesn't make sense I know since I did look at `foreach`. Nevertheless it was only when I debugged that I realized that just above is `if (!done)` and not `while (!done)`.
Feel free to ignore this if you had some strong reason for the naming.
=> Fix 'foreach' comment in AsyncSubscriber and rename SyncSybscriber.foreach to whenNext

CopyrightWaivers.txt, README.md
Spelling of the company name is Red Hat, not RedHat.
=> Update README.md ~ spelling of the company name Red Hat

.travis.yml
One more try… apparently the magic word for sudo is "required", and not "true", whereas to turn it off, it is "false" … :S
=> Third attempt at fixing the Travis builds

.travis.yml, tck/README.md, tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/main/java/org/reactivestreams/tck/SubscriberWhiteboxVerification.java, tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java, tck/src/test/java/org/reactivestreams/tck/IdentityProcessorVerificationTest.java
Supersedes #309 because TravisCI is broken
=> +tck #308 allow configuring "no events during N time" separately

tck/src/test/java/org/reactivestreams/tck/PublisherVerificationTest.java
Semantics remain exactly the same, the error we're testing here is about
signaling one more element if request comes in again (which we'll do
anyway, regardless of status of this flag).
cheers to @Silv3rcircl3 for not duplicating this silly mistake in .NET port of TCK
cc @viktorklang 
See https://github.com/reactive-streams/reactive-streams-dotnet/pull/9/files#r68312787
Reviewers: expand snippet UP, to see what this change is about (and read the comment above this if)
=> =tck fixes minor misalignment between code and comment, found via .NET port

api/src/main/java/org/reactivestreams/Subscription.java
As I understand it `cancel` can be called synchronously also. Removed the part of the javadoc that says that `cancel` is called asynchronously.
=> adjust Subscription.cancel javadoc

CopyrightWaivers.txt, examples/src/main/java/org/reactivestreams/example/unicast/AsyncSubscriber.java
This pull request fixes a minor typo in a comment.
=> Fix a typo in org.reactivestreams.example.unicast.AsyncSubscriber

README.md
Dear @reactive-streams/contributors,
we've been talking for ages about adding an intents-section for every spec rule,
and during a cross-atlantic flight I finally found the time to write this up.
This PR is not intended for merging, but is rather a conversation to figure out the proper wording/intent for each of the spec rules.
The idea would be to iterate on that, and then I'll create a real PR against the README.md
Additionally, I've found some opportunities to clarify some of the spec rules, and I think that'd be of general interest.
NONE OF THE THINGS PROPOSED HEREIN CHANGES ANY SEMANTICS OF THE SPEC WHATSOEVER.
√
=> Documentation of intent for each and every rule

build.gradle
To have a tangible PR to talk about.
Probably enough to resolve https://github.com/reactive-streams/reactive-streams-jvm/issues/349
Would be followed up with change to 1.0.1 eventually.
If for some reason that `.release` was on purpose and is really needed please chime in @smaldini
=> =build #349 equal osgi manifest version as real version

tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java
Make `required_spec309_requestNegativeNumberMustSignalIllegalArgumentException` deterministically request -1 as the negative number.
=> TCK: Request -1 in 309 instead of a random non-positive number

tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/main/java/org/reactivestreams/tck/support/PublisherVerificationRules.java
This PR adds some explanation about what each `PublisherVerificationRules` methods do in respect to their expectation and request/emission pattern that could help tracking down the errors in the `Publisher` under test and tries to hint about what could be wrong in that `Publisher`.
I run into situations when there were errors in my `Publisher`s but the error response didn't help much and had to look into what the test actually did (in C# it was even harder due to lack of nicely linked TCK sources) and single-stepping through is cumbersome because of the several layers of test equipment within the TCK.
Let me address some concerns upfront:
Mainly because the Javadoc would need duplication for `IdentityProcessorVerification` which is double maintenance work.
Knowing the request pattern or …
=> Add Javadoc explanation to the TCK test methods about what they do

tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/test/java/org/reactivestreams/tck/RangePublisherTest.java
Some of the `PublisherVerification` tests didn't cancel the `Subscription` when they stopped consuming the source.
> 2.6: A Subscriber MUST call `Subscription.cancel()` if it is no longer valid to the `Publisher` without the `Publisher` having signaled `onError` or `onComplete`.
> :bulb:	The intent of this rule is to establish that `Subscriber`s **cannot just throw `Subscriptions` away** when they are no longer needed, they have to call `cancel` so that resources held by that `Subscription` can be safely, and timely, reclaimed.
=> Fix missing cancel() in tests that don't consume the entire source

README.md
@reactive-streams/contributors No review needed, the README pointed links to 1.0.0.RC5 but should currently be 1.0.0
=> Repointing links to sources in README to current main release

tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java
The original issue #278 has been open for almost 2 years with no one else commenting.
Improving the status quo by removing the partial sentence for now.
=> Removes a partial sentence in the javadoc

tck/src/main/java/org/reactivestreams/tck/SubscriberBlackboxVerification.java, tck/src/main/java/org/reactivestreams/tck/support/SubscriberBlackboxVerificationRules.java
This PR adds textual explanations to the `SubscriberBlackBoxVerificationRules` and also removes the `// Verifies rule:` comments from `SubscriberBlackBoxVerification`.
The description contains a **Notes:** section which could be considered as problems, bugs or opportunities within the TCK tests. I think most of them are spec violations by the test infrastructure itself.
I haven't looked into `SubsriberWhiteBoxVerification` implementation to see what's different from the black-box version and thus the test need individual explanations or not.
=> SubscriberBlackboxVerificationRules explained

tck/src/main/java/org/reactivestreams/tck/SubscriberBlackboxVerification.java, tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java
Follow up to things found in https://github.com/reactive-streams/reactive-streams-jvm/pull/362
=> =tck #362 signal onComplete in 201 blackbox verification

tck/src/main/java/org/reactivestreams/tck/SubscriberBlackboxVerification.java, tck/src/test/java/org/reactivestreams/tck/SubscriberBlackboxVerificationTest.java
Cleanup to things found in #362
=> +tck #362 complete subscriber under test once done in 205

tck/src/main/java/org/reactivestreams/tck/SubscriberBlackboxVerification.java
Follow up to #362, the TCK violated the spec without good reason (wasn't testing for anything like that)
=> =tck #362 blackbox 209 must issue onSubscribe before any other signal

CopyrightWaivers.txt, tck/src/main/java/org/reactivestreams/tck/IdentityProcessorVerification.java, tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java, tck/src/main/java/org/reactivestreams/tck/support/PublisherVerificationRules.java, tck/src/test/java/org/reactivestreams/tck/PublisherVerificationTest.java
* now test verifies https://github.com/reactive-streams/reactive-streams-jvm#1.11 and
https://github.com/reactive-streams/reactive-streams-jvm#1.5 for publishers, if they support multiple subscribers.
=> optional_spec111 test addition.

README.md, RELEASE-NOTES.md, build.gradle, tck/README.md
=> Prepare 1.0.1

tck/src/main/java/org/reactivestreams/tck/IdentityProcessorVerification.java, tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java, tck/src/main/java/org/reactivestreams/tck/support/PublisherVerificationRules.java, tck/src/test/java/org/reactivestreams/tck/PublisherVerificationTest.java
Resolves https://github.com/reactive-streams/reactive-streams-jvm/issues/384 in the TCK, existing impls will remain to pass since they were already referring to 3.9
=> =tck #384 dont check for cause message when checking 3.9

README.md, RELEASE-NOTES.md, build.gradle, tck/README.md
Wrapping up the 1.0.1 commit here.
@reactive-streams/contributors,
Planning on shipping on the 9th of August.
Includes https://github.com/reactive-streams/reactive-streams-jvm/pull/389 since 1.0.1-RC2
Sounds good?
√
=> Preparing 1.0.1

flow-bridge/src/main/java/org/reactivestreams/ReactiveStreamsFlowBridge.java, flow-bridge/src/test/java/org/reactivestreams/ReactiveStreamsFlowBridgeTest.java
This PR exposes the `Subscriber` conversion through the `ReactiveStreamsFlowBridge` API.
=> Java 9 Flow bridge: add Subscriber converters

README.md
=> Addressing typos and elaboration requests in the spec.

CopyrightWaivers.txt, api/build.gradle, examples/build.gradle, flow-adapters/build.gradle, tck-flow/build.gradle, tck/build.gradle
Including @kiiadi's commit here.
=> Wip add modulename √

tck-flow/src/test/java/org/reactivestreams/tck/flow/SubmissionPublisherTest.java
This PR adds a `SubmissionPublisher` TCK test to the `flow-tck` subproject.
I've tested it with both Java 9.0.1 (via Gradle) and the custom patch from [Doug Lea](https://github.com/reactive-streams/reactive-streams-jvm/issues/413#issuecomment-347036550)'s comment (via IntelliJ's own test runner configured).
=> Add SubmissionPublisher TCK test

tck/README.md, tck/src/main/java/org/reactivestreams/tck/IdentityProcessorVerification.java, tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java, tck/src/test/java/org/reactivestreams/tck/LockstepProcessorTest.java
This PR fixes the TCK to support request-coordinating `Processor` implementations. These kinds of `Processor`s may either 
- coordinate the request amounts of their `Subscriber`s and request only from upstream when all `Subscriber`s requested something; or
- coordinate emissions, requesting a bounded amount upfront from the upstream and then emitting only when all `Subscriber`s have requested something.
From the downstream `Subscriber`s' perspective, both manifest as lack of emissions.
The `IdentityProcessorVerification.doesCoordinatedEmission()` added will affect
- `required_spec104_mustCallOnErrorOnAllItsSubscribersIfItEncountersANonRecoverableError`
- `required_mustRequestFromUpstreamForElementsThatHaveBeenRequestedLongAgo`
By adjusting the test request pattern to request on both …
=> Allow request-coordinating Processor implementations to pass the TCK

README.md, RELEASE-NOTES.md, build.gradle, tck-flow/README.md, tck/README.md, tck/src/test/resources/testng.yaml
@reactive-streams/contributors  This is the preparation for 1.0.2-RC1,
I'd like to issue it before the end of the week, so please provide feedback ASAP if you're interested in vetting the release notes etc.
=> Preparations for 1.0.2-RC1—incl. release notes.

tck/src/main/java/org/reactivestreams/tck/SubscriberWhiteboxVerification.java, tck/src/test/java/org/reactivestreams/tck/SubscriberNoRegisterOnSubscribeTest.java
This PR makes sure the TCK checks if the `WhiteboxSubscriberProbe.registerOnSubscribe()` was called before any test body tries to use the (unavailable) puppet, crashing with `NullPointerException` and hiding the fact the method call was missing.
Fixes: #416
=> TCK: Fail early if registerOnSubscribe is not called

tck-flow/src/main/java/org/reactivestreams/tck/flow/IdentityFlowProcessorVerification.java, tck-flow/src/test/java/org/reactivestreams/tck/flow/LockstepFlowProcessorTest.java, tck/src/main/java/org/reactivestreams/tck/IdentityProcessorVerification.java
This PR fixes the `IdentityFlowProcessorVerification` class as it did not properly use the `FlowAdapters` and required the developer to specify helper structures manually and unnecessarily.
The `LockstepFlowProcessorTest` was ported as a native `Flow.Processor` implementation to ensure `IdentityFlowProcessorVerification` is properly implementable.
Related: https://github.com/reactive-streams/reactive-streams-jvm/issues/413#issuecomment-349640154
=> 1.0.2-RC1: Fix the IdentityFlowProcessorVerification class

tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java, tck/src/test/java/org/reactivestreams/tck/PublisherVerificationTest.java, tck/src/test/java/org/reactivestreams/tck/flow/support/TCKVerificationSupport.java
=> Ensure TCK passes with empty publisher that synchronously completes

CopyrightWaivers.txt, tck-flow/src/main/java/org/reactivestreams/tck/flow/IdentityFlowProcessorVerification.java
Fixes #425
IdentityFlowProcessorVerification.createFailedProcessor is allowed to return null, but the TCK throws an NPE if it does. This introduces a null check to ensure that doesn't happen.
=> Fix NPE for null failed processor in IdentityFlowProcessorVerification

tck/src/main/java/org/reactivestreams/tck/IdentityProcessorVerification.java
Fixes #278.
This was already fixed for `PublisherVerification`, but the fix wasn't done on the same method on `IdentityProcessorVerification`.
=> Fixed javadocs for skipStochasticTests

tck/src/main/java/org/reactivestreams/tck/SubscriberWhiteboxVerification.java, tck/src/test/java/org/reactivestreams/tck/SubscriberWhiteboxVerificationTest.java
Fixes #277.
Fixes two whitebox subscriber tests where they weren't waiting for demand before signaling onNext.
=> Wait for demand before signaling onNext

tck/src/main/java/org/reactivestreams/tck/SubscriberWhiteboxVerification.java
This addresses some of the problem raised in #280.
=> Clarified the expected behaviour for triggerRequest

tck/src/main/java/org/reactivestreams/tck/IdentityProcessorVerification.java, tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java, tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java
=> Making debug message formatting disabled when debug is disabled

CopyrightWaivers.txt, README.md
This PR intends to rollback missed description for *thread-safe* notion required for 3.7 rule and fixes some double period among latest updates
=> rollbacks thread-safe notion and fixes typos

CopyrightWaivers.txt, gradle/wrapper/gradle-wrapper.properties
Motivation:
The existing gradlew wrapper version doesn't support JDK11.
Modifications:
- Update to 4.10.3 which does support JDK11.
Result:
TCK can be built on JDK11.
=> Update gradlew wrapper to 4.10.3

tck-flow/README.md, tck/README.md, tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java
Motivation:
`defaultTimeoutMillis` is typically used as a "max time to wait until an expected event occurs". For example this value is used as the argument to a `ArrayBlockingQueue#poll(timeout)` [1][2][3] method call and therefore when things work as expected you rarely wait this full duration. However [Receptacle#expectError](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java#L1030) does a `Thread.sleep(..)` and then checks if there is something present in the error list (which is a [CopyOnWriteArrayList](https://github.com/reactive-streams/reactive-streams-jvm/blob/master/tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java#L45)). The value for the sleep is typically derived from …
=> TCK: Receptacle#expectError timeout approach

build.gradle
Motivation:
Add a publishing task in the top level gradle file that allows for publishing
to the local maven repository.
Modifications:
- When `./gradlew publishToMavenLocal` is invoked we should publish to the local
maven repo for: reactive-streams, reactive-stream-tck,
reactive-streams-tck-flow, and reactive-streams-examples
Result:
`./gradlew publishToMavenLocal` publishes artifacts to the local maven
repository.
Fixes https://github.com/reactive-streams/reactive-streams-jvm/issues/456
=> Enable ./gradlew publishToMavenLocal

tck/src/main/java/org/reactivestreams/tck/SubscriberWhiteboxVerification.java
See #453 and https://github.com/reactive-streams/reactive-streams-jvm/pull/441#discussion_r288380996
=> Allow triggerRequest and signalCancel to be coalesced

tck/src/main/java/org/reactivestreams/tck/PublisherVerification.java
=> Fix a typo in spec101 error message

tck/src/main/java/org/reactivestreams/tck/SubscriberBlackboxVerification.java, tck/src/main/java/org/reactivestreams/tck/SubscriberWhiteboxVerification.java, tck/src/test/java/org/reactivestreams/tck/SubscriberBlackboxVerificationTest.java, tck/src/test/java/org/reactivestreams/tck/SubscriberWhiteboxVerificationTest.java
Originally, the TCK verifying rule §2.3 would fail if the call stack contained any method named `onComplete` or `onError`, even if they were not on the call chain initiated by the test's `onError`/`onComplete`.
Related #481, https://github.com/eclipse/microprofile-reactive-streams-operators/issues/131
Resolves #460
=> Fix TCK §2.3 verification for when a legit call is made with onError/onComplete method name in the stacktrace

tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java
=> Correcting the wrong default timeout parameter in TestEnvironment ctor

tck/build.gradle
Seemed like the lowest resistance path was to upgrade TestNG itself.
=> Addresses #528 by upgrading testng to 7.3.0

.github/workflows/ci.yml
Java 6 is no longer available as target in 13. Removing that build target.
=> Do not build on JDK 13.

examples/src/test/java/org/reactivestreams/example/unicast/AsyncRangePublisherTest.java, tck/src/main/java/org/reactivestreams/tck/TestEnvironment.java
Motivation:
The timeout calculation decrementing `totalTimeoutRemainingNs` is incorrect which results in premature timeouts and test failures.
=> TestEnvironment: Fix timeout arithmetic
